name: Jobs

on: [push]

env:
  CARGO_TERM_COLOR: always
  rust_toolchain: nightly-2022-08-05

jobs:
  basic-test:
    runs-on: ubuntu-latest
    container:
      image: duskmoon/dev-env:rcore-ci
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          qemu-system-riscv64 --version
          rustup target add riscv64gc-unknown-none-elf
          git config --global --add safe.directory /__w/rCore-Tutorial-Code-2023S/rCore-Tutorial-Code-2023S
          git clone https://github.com/LearningOS/rCore-Tutorial-Checker-2023S.git ci-user
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2023S.git ci-user/user
          ID=`git rev-parse --abbrev-ref HEAD | grep -oP 'ch\K[0-9]'`
          cd ci-user && make test CHAPTER=$ID passwd=${{ secrets.BASE_TEST_TOKEN }}